import 'package:aikon/controller/auth_controller.dart';
import 'package:aikon/controller/offer_controller.dart';
import 'package:aikon/model/offer_model.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:get/get.dart';

final _offerController = Get.find<OfferController>();
final _authController = Get.find<AuthController>();

class FirebaseOfferService {
  static final FirebaseFirestore db = FirebaseFirestore.instance;
  static String offerCollection = "offers";

  // Add Offer
  static Future<void> createOffer() async {
    _offerController.loadingOtherOffers.value = true;

    String randomAutoGeneratedId = db.collection(offerCollection).doc().id;
    var offerData = {
      "id": randomAutoGeneratedId,
      "isSell": _offerController.isSell.value,
      "title": _offerController.titleController.text,
      "subtitle": _offerController.subTitleController.text,
      "description": _offerController.descriptionController.text,
      "country": _offerController.countryController.text,
      "city": _offerController.cityController.text,
      "images": _offerController.selectedImageUrlList,
      "channels": _offerController.channelList,
      "isAnonymous": _offerController.postAnonymously.value,
      "userId": FirebaseAuth.instance.currentUser!.uid,
      "createdAt": DateTime.now(),
    };

    try {
      await db
          .collection(offerCollection)
          .doc(randomAutoGeneratedId)
          .set(offerData);
      _offerController.loadingOtherOffers.value = false;
      print("Offer Added");
    } catch (e) {
      _offerController.loadingOtherOffers.value = false;
      print("Failed to Add Offer:  $e");
    }
  }

  // Get all Offers Details
  static Future<void> getAllMyOffers() async {
    _offerController.loadingMyOffers.value = true;
    _offerController.myOffersListings.clear();

    try {
      var offerSnapshot = await db.collection(offerCollection).get();
      _offerController.loadingMyOffers.value = false;

      for (var doc in offerSnapshot.docs) {
        Map<String, dynamic> data = doc.data();
        data["id"] = doc.id;
        // data["imagesList"] = List<String>.from(data["imagesList"]);

        if (FirebaseAuth.instance.currentUser!.uid == data["userId"]) {
          _offerController.myOffersListings.add(OfferModel.fromJson(data));
        }
      }

      print("All My Offers Getting Done");
    } catch (e) {
      _offerController.loadingMyOffers.value = false;
      print("Failed to Get All My Offers:  $e");
    }
  }

  static Future<void> getAllOtherOffers() async {
    _offerController.otherOffersListings.clear();

    try {
      var offerSnapshot = await db.collection(offerCollection).where("isSell",
          whereIn: [_offerController.toggleStateIsSell.value]).get();

      for (var doc in offerSnapshot.docs) {
        Map<String, dynamic> data = doc.data();
        data["id"] = doc.id;

        if (FirebaseAuth.instance.currentUser!.uid != data["userId"]) {
          _offerController.otherOffersListings.add(OfferModel.fromJson(data));
        }
      }

      print("All Other Offers Getting Done");
    } catch (e) {
      print("Failed to Get All Other Offers:  $e");
    }
  }

// Update Offers Details
  static Future<void> updateOffer(String id) async {
    _offerController.loadingOtherOffers.value = true;
    var updateOfferData = {
      "isSell": _offerController.isSell.value,
      "title": _offerController.titleController.text,
      "subtitle": _offerController.subTitleController.text,
      "description": _offerController.descriptionController.text,
      "country": _offerController.countryController.text,
      "city": _offerController.cityController.text,
      "images": _offerController.selectedImageUrlList,
      "channels": _offerController.channelList,
      "isAnonymous": _offerController.postAnonymously.value,
      "userId": FirebaseAuth.instance.currentUser!.uid,
      "createdAt": DateTime.now(),
    };

    try {
      await db.collection(offerCollection).doc(id).update(updateOfferData);
      _offerController.loadingOtherOffers.value = false;
      print("Offer Updated");
    } catch (e) {
      _offerController.loadingOtherOffers.value = false;
      print("Failed to Update Offer:  $e");
    }
  }

  // Delete Offers
  static Future<void> deleteOffer(String id) async {
    _offerController.loadingMyOffers.value = true;
    try {
      await db.collection(offerCollection).doc(id).delete();
      _offerController.loadingMyOffers.value = false;
      print("Offer Deleted");
    } catch (e) {
      _offerController.loadingMyOffers.value = false;
      print("Failed to Delete Offer:  $e");
    }
  }

  static Future<void> getAllFavouriteOffers() async {
    _offerController.favouriteOfferList.clear();

    try {
      final favouriteRef = db.collection(offerCollection);
      final favourite = await favouriteRef
          .where("id", whereIn: _authController.favouriteIdList)
          .get();

      for (var doc in favourite.docs) {
        Map<String, dynamic> data = doc.data();

        _offerController.favouriteOfferList.add(OfferModel.fromJson(data));
      }

      print("All Favourite Offers Getting Done");
    } catch (e) {
      print("Failed to Get All favourite Offers:  $e");
    }
  }
}
